---
- name: 'Install Percona Repository'
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: 'Install Percona Toolkit'
  yum:
    state: present
    name: percona-toolkit

- name: 'Install MySQL Client'
  yum:
    state: present
    name: Percona-Server-client-57
