---
- name: Apply configuration to all servers instances
  hosts: all
  roles:
    - hostname
    - bash
    - ssh

- name: Apply configuration to proxysql instances
  hosts: localhost
  vars:
    tier: "{{ lookup('env','TIER') }}"
  roles:
    - proxysql
  when: tier == 'proxysql'
