---
- name: Apply configuration to all servers instances
  hosts: all
  vars:
    project: "{{ lookup('env','PROJECT') }}"
    env: "{{ lookup('env','ENVIRONMENT') }}"
    tier: "{{ lookup('env','TIER') }}"
    role: "{{ lookup('env','ROLE') }}"
  roles:
    - hostname
    - bash
    - ssh
  tasks:
  - include_vars: "vars/{{ project }}-{{ env }}-{{ tier }}-{{ role }}.yml"
  - include_role:
      name: "{{ tier }}"
    ignore_errors: yes
